# Image Representation

In [35]:
import cv2
import numpy as np

In [36]:
img=cv2.imread('lenna.png')

In [37]:
print(img)

[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]


In [38]:
type(img)

numpy.ndarray

In [39]:
img.shape

(512, 512, 3)

In [40]:
#rows=hight   columns=width   3 chaell=BGR

Create a image manually by using array

2 * 2 pixels

2 black pixels

2 white pixels

In [41]:
[
    [[0,0,0],[255,255,255]],
    [[0,0,0],[255,255,255]]
]



[[[0, 0, 0], [255, 255, 255]], [[0, 0, 0], [255, 255, 255]]]

In [42]:
#Blue green red   [0,0,0]    0-255

In [43]:
#fisrt row of our image

In [44]:
print(img[0])

[[125 137 226]
 [125 137 226]
 [133 137 223]
 ...
 [122 148 230]
 [110 130 221]
 [ 90  99 200]]


In [45]:
# we want to create random pixels
import random

In [46]:
for i in range(100):
    for j in range(img.shape[1]):
        img[i][j]=[random.randint(0,255),random.randint(0,255),random.randint(0,255)]
        
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Use Slice to manipulate Image

In [49]:
cv2.imshow('Image',img[100:300,100:300])
cv2.waitKey(0)
cv2.destroyAllWindows()