In [7]:
import numpy as np
import cv2 as cv

In [8]:
img=cv.imread('./images/flamingo.jpg')

In [9]:
print(img)

[[[ 79  85 120]
  [ 85  91 128]
  [ 86  89 134]
  ...
  [ 51  53  84]
  [ 57  56  90]
  [ 61  60  94]]

 [[ 43  51  81]
  [ 49  56  89]
  [ 49  54  93]
  ...
  [ 80  82 112]
  [ 86  88 119]
  [ 91  93 124]]

 [[ 38  49  71]
  [ 47  57  81]
  [ 52  61  88]
  ...
  [ 80  84 112]
  [ 87  92 117]
  [ 93  98 123]]

 ...

 [[ 41  89  60]
  [ 30  80  50]
  [ 16  68  38]
  ...
  [123 103  92]
  [120 100  89]
  [119  99  88]]

 [[ 47  95  66]
  [ 39  89  59]
  [ 26  78  48]
  ...
  [ 46  48  36]
  [ 44  46  34]
  [ 42  44  32]]

 [[ 49  97  68]
  [ 44  94  64]
  [ 34  86  56]
  ...
  [ 54  66  54]
  [ 54  66  54]
  [ 55  67  55]]]


In [10]:
img.shape

(280, 400, 3)

In [12]:
cv.imshow('falmingo',img)
cv.waitKey(10000)#milliseconds
cv.destroyAllWindows()

In [15]:
cv.imshow('falmingo',img)
cv.waitKey(0)#zero 0 key
cv.destroyAllWindows()

In [14]:
#save an image

In [16]:
cv.imwrite('test.jpg',img)

True