In [3]:
import numpy as np
import cv2 

In [4]:
img=cv2.imread('./Model/faces.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
face_detection_model=cv2.dnn.readNetFromCaffe('./Model/deploy.prototxt.txt','./Model/res10_300x300_ssd_iter_140000.caffemodel')

In [61]:
def face_detection_dnn(img):
    #step1-blob from image
    blob=cv2.dnn.blobFromImage(img,1,(300,300),(104,177,123),swapRB=True)

    #step2-set blob as input
    face_detection_model.setInput(blob)

    #step3-get the output
    detections=face_detection_model.forward()

    #step4-drawing bounding box out of the face detected
    image-img.copy()
    h,w=image.shape[:2]
    for i in range(0,detections.shape[2]):
        confidence=detections[0,0,i,2]
        if confidence>0.5:
            #diagonal points 3:7
            box=detections[0,0,i,3:7]*np.array([w,h,w,h])
            box=box.astype('int')
            p1=(box[0],box[1])
            p2=(box[2],box[3])
            #draw rectangle
            cv2.rectangle(image,p1,p2,(0,0,255),2)

            text='score: {:.0f} %'.format(confidence*100)
            cv2.putText(image,text,p1,cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,1,(255,255,255),1)

    #cv2.imshow('image',image)
    #cv2.waitKey(0)
    #cv2.destroyAllWindows()
    return image

In [62]:
img_detect=face_detection_dnn(img)
cv2.imshow('image',img_detect)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
detections.shape

(1, 1, 200, 7)

In [15]:
image=img.copy()
image.shape[:2]


(349, 620)

In [19]:
detections[0,0,:,2]

array([0.9840151 , 0.94294983, 0.93852323, 0.64889914, 0.1409829 ,
       0.1306343 , 0.11604731, 0.11102255, 0.1058416 , 0.10531221,
       0.10299055, 0.10263243, 0.09813836, 0.09648059, 0.0955316 ,
       0.09512691, 0.09392449, 0.09362706, 0.0935647 , 0.09172019,
       0.09124843, 0.09117849, 0.09087311, 0.0906086 , 0.08918419,
       0.08904949, 0.08888301, 0.08879568, 0.08844741, 0.08816624,
       0.08814394, 0.0879451 , 0.08781833, 0.08756871, 0.08745909,
       0.08719447, 0.08707898, 0.08688767, 0.08642443, 0.08640453,
       0.0862636 , 0.08612955, 0.0861181 , 0.08571972, 0.0851794 ,
       0.08501004, 0.08478802, 0.08475907, 0.08428978, 0.08386167,
       0.08380896, 0.08372811, 0.08364581, 0.08363985, 0.08363832,
       0.08347051, 0.08316626, 0.08315517, 0.08275096, 0.08264603,
       0.08261672, 0.08257951, 0.0824748 , 0.08237419, 0.08219832,
       0.0821361 , 0.08212148, 0.08194728, 0.08194519, 0.08187522,
       0.08181036, 0.08181012, 0.08176288, 0.08166607, 0.08151

In [22]:
# x,y, w,h bounding box of face
detections[0,0,1,3:7]

array([0.19488767, 0.1623927 , 0.27129608, 0.35642   ], dtype=float32)

In [23]:
image.shape

(349, 620, 3)

In [26]:
w,h=image.shape[:2]
print(w)
print(h)

349
620


In [27]:
np.array([w,h,w,h])

array([349, 620, 349, 620])

In [30]:
#denormalize values
detections[0,0,1,3:7]*np.array([w,h,w,h])

array([120.83035409,  56.67505428, 168.20357203, 124.3905836 ])

In [35]:
box=detections[0,0,1,3:7]*np.array([w,h,w,h])
box=box.astype('int')
box

array([120,  56, 168, 124])

In [37]:
#points
p1=(box[0],box[1])
p2=(box[2],box[3])
print(p1)
print(p2)

(120, 56)
(168, 124)
